spring:
  application:
    name: turbine

server:
  port: 8765

management:
  port: 9766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

turbine:
  app-config: service-feign
  aggregator:
    clusterConfig: default
  combine-host-port: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
  cluster-name-expression: new String("default")