eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30
      hostname: localhost
  metadata-map:
        cluster: service-feign

feign:
  hystrix:
    enabled: true

server:
  port: 8086

spring:
  application:
    name: service-feign

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
