eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: 8881
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh