server:
  port: 8769

spring:
  application:
    name: gateway
  cloud:
      gateway:
        routes:
        - id: service-feign
          uri: lb://service-feign
          predicates:
          - Path= /service-feign/**
          filters:
          - RewritePath=/service-feign/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: localhost